services:
  api:
    build: .
    container_name: pfa_api
    volumes:
      - .:/app  # Maps your local folder to /app inside Docker
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  dashboard:
    build: .
    container_name: pfa_dashboard
    depends_on:
      - api
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0